baseURL = 'https://haarlekin.at/'
locale = 'de-DE'
title = 'Haarlekin - Friseursalon Innsbruck'
theme = 'haarlekin-theme'

[params]
  subtitle = 'Friseursalon'
  phone = '0512 57 46 75'
  phone_tel = '+43512574675'
  address = 'Heiliggeiststrasse 2'
  address_link = 'https://goo.gl/maps/iG89XmewspYNkRXy6'
  email = 'haarlekin@gmx.at'
  instagram = 'https://www.instagram.com/hell_alexandra/'
  facebook = 'https://www.facebook.com/designs.for.art'

[cascade]
  [cascade."content/art"]
    type = "art"
  [cascade."content/award"]
    type = "award"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Beiträge'
    pageRef = '/beitraege'
    weight = 20

  [[menus.main]]
    name = 'Art'
    pageRef = '/art'
    weight = 30

  [[menus.main]]
    name = 'Awards'
    pageRef = '/award'
    weight = 40

  [[menus.main]]
    name = 'Salon'
    pageRef = '/salon'
    weight = 50
